export const traerTiquetesComprados = [
    {
      id: 1,
      codeSeat: "A7",
      idCinema: 2,
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 2,
      codeSeat: "A8",
      idCinema: 2,
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 3,
      codeSeat: "A9",
      idCinema: 2,
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 4,
      codeSeat: "B7",
      idCinema: 2,
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "11:00",
    },
    {
      id: 5,
      codeSeat: "B8",
      idCinema: 2,
      idSala: 2,
      idFuncion: 2,
      date: "8 de agosto",
      hour: "13:00",
    },
  ];